---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################


- name: Load a variable file based on the OS type, or a default if not found
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "001_version/001-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "002_distribution/002-{{ ansible_distribution }}.yml"
    - "003_os_family/003-{{ ansible_os_family }}.yml"
    - "999-default.yml"
