---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################

- name: Import configure language
  ansible.builtin.import_tasks:
    file: configure-lang.yml
  when: config_system_locale is defined and config_system_language is defined

- name: Import setup Hetzner private network
  ansible.builtin.import_tasks:
    file: setup-hetzner-private-network.yml
  when:
    - dc_provider | lower == 'hetzner'

- name: Import setup hosts file
  ansible.builtin.import_tasks:
    file: setup-hosts-file.yml

- name: Import setup motd
  ansible.builtin.import_tasks:
    file: setup-motd.yml

- name: Import setup timezone
  ansible.builtin.import_tasks:
    file: setup-timezone.yml
  when: timezone is defined

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Setup swap
  ansible.builtin.import_tasks:
    file: setup-swap.yml
  when:
    - swap_enabled | default(false)
    - dc_provider | lower == 'hetzner'

- name: Remove swap
  ansible.builtin.import_tasks:
    file: remove-swap.yml
  when:
    - not swap_enabled | default(false)
    - dc_provider | lower == 'hetzner'

- name: Set fact 'basic_setup_done' to true
  ansible.builtin.set_fact:
    basic_setup_done: true
