---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################

- name: Register swap_file variable
  ansible.builtin.set_fact:
    swap_file: "{{ swap_file_path | default('/swap') }}"
  tags: swap

- name: Swap off 
  ansible.builtin.command:
    cmd: "swapoff -a"

- name: Remove swap file
  ansible.builtin.file:
    path: "{{ swap_file }}"
    state: absent

- name: Remove swap from fstab
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file }}"
    line: "{{ swap_file }} none swap sw 0 0"
    state: absent
