---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################

- name: Copy hosts to servers
  ansible.builtin.template:
    src: ./templates/etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
