---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################

- name: Copy 61-private-network.cfg to servers
  ansible.builtin.template:
    src: ./templates/etc/network/interfaces.d/61-private-network.cfg.j2
    dest: /etc/network/interfaces.d/61-private-network.cfg
    owner: root
    group: root
    mode: '0644'
  notify: Restart networking
