---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################

- name: Register swap_file variable
  ansible.builtin.set_fact:
    swap_file: "{{ swap_file_path | default('/swap') }}"
  tags: swap

- name: Check if swap file already exists
  ansible.builtin.stat:
    path: "{{ swap_file }}"
  register: swap_file_check

- name: Get size of swap file in GB if it exists
  ansible.builtin.set_fact:
    swap_file_size: "{{ (swap_file_check.stat.size / 1024 / 1024 / 1024) | int }}"
  when: swap_file_check.stat.exists

- name: Output swap file size
  ansible.builtin.debug:
    msg: "Swap file size: {{ swap_file_size }} GB"
  when: swap_file_check.stat.exists

- name: Check if swap is on or off
  ansible.builtin.shell:
    cmd: "swapon --show"
  register: swap_status
  changed_when: swap_status.stdout != ""

- name: Swap off if current swap file size is different from the desired size and swap is on
  ansible.builtin.command:
    cmd: "swapoff -a"
  when: swap_file_check.stat.exists and (swap_file_size | int) != (swap_size | int) and swap_status.stdout != ""
  register: swap_off

- name: Remove swap file if current swap file size is different from the desired size
  ansible.builtin.file:
    path: "{{ swap_file }}"
    state: absent
  when: swap_file_check.stat.exists and (swap_file_size | int) != (swap_size | int)
  register: swap_file_remove

- name: Create swap file if it does not exist
  ansible.builtin.command:
    cmd: "fallocate -l {{ swap_size }}G {{ swap_file }}"
  when: not swap_file_check.stat.exists or swap_file_remove.changed

- name: Set permissions on swap file
  ansible.builtin.file:
    path: "{{ swap_file }}"
    mode: 0600

- name: Format swap file
  ansible.builtin.command:
    cmd: "mkswap {{ swap_file }}"
  when: not swap_file_check.stat.exists or swap_file_remove.changed

- name: Turn on swap
  ansible.builtin.command:
    cmd: "swapon {{ swap_file }}"
  when: not swap_file_check.stat.exists or swap_file_remove.changed

- name: Add swap file to fstab
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file }}"
    line: "{{ swap_file }} none swap sw 0 0"
    state: present

- name: Set swapiness
  ansible.builtin.sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness | default(10) }}"
    state: present
    reload: true
  when: swap_swappiness is defined
