---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################

- name: Update package cache
  ansible.builtin.yum:
    update_cache: yes

- name: Update all packages to their latest version
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: Remove unneeded dependencies
  ansible.builtin.yum:
    autoremove: true
