---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################

- name: Restart networking
  service:
    name: networking
    state: restarted

- name: Restart unattended-upgrades
  service:
    name: unattended-upgrades
    state: restarted
